name =input("enter your name:")
age = input("enter your age:")
print("hello" +"  " + name + " ""your age is"+ " "+ age  )
num =input("enter your first number:")
num2 = input("enter your second number:")
sum = int(num) + int(num2)
print(sum)  